spring:
  application:
    name: employee-service

  datasource:
    username: postgres
    password: postgre1488rp
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/company

  liquibase:
    default-schema: employees
    change-log: file:employee-service/db-employee/src/main/resources/db/changelog/db.changelog-master.yaml

  boot:
    admin:
      client:
        url: http://localhost:8083
        instance:
          name: ${spring.application.name}
          service-host-type: ip
        enabled: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 15
        minimumNumberOfCalls: 10
        failureRateThreshold: 100
        waitDurationInOpenState: 6000
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 50

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

preliquibase:
  sql-script-references: file:employee-service/db-employee/src/main/resources/preliquibase/postgresql.sql

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
#    zipkin:
#      tracing:
#        endpoint: http://127.0.0.1:9411/api/v2/spans
#    tracing:
#      sampling:
#        probability: 1.0